bn_wm = false
nosleep = true
dc_nervous = false
dashforward = true
hardattrb = true
psive_fb = true
sk_caskill = true
sk_gattshot = true
sk_smai = true
sk_noburn = true
zb_pblock = true
zb_bblock = true
zb_allbreaker = true
zb_newabi = true
zb_ttnt = false
zb_noburn = true
zb_smoften = true
cr_smai = false
cr_ssnow = true
cr_sap = true
cr_disguide = true
sp_shtweb = true
em_curse = true
em_caskill = true
ws_caskill = true
dr_caskill = true
dr_curse = true
mw_enable = true
mw_burning = true
mw_freeze = true
mw_leviation = true
mw_spread = true
mw_drop = true
jk_rsum = true
bl_caskill = true
bl_spawnao = true
bl_usecurse = true
wm_rsum = true
slime_sb = true
sfish_ife = true
vd_statue = true
ws_tc = true
ptom_sleep = false
ptom_carry = false
ptom_rsum = false
mob_inv = true
gh_smul = true
ilu_rsum = true
